### ISSUE TITLE
no zero at the beginning of digits on month and date

### ISSUE THREAD

**Issue by woots29** [biohzrdmx/jQuery.DatePicker#9]
If someone needs to have zeroes in the beginning of date/months, try this:
_(MM/DD/YYYY) format_
```
 dateFormat: function(e) {
                function zr(h) {
                    return (h < 10 ? "0" : "") + h;
                }
                return zr(e.getMonth() + 1) + "/" + zr(e.getDate()) + "/" + e.getFullYear()
            },
```

**Comment by biohzrdmx** [comment]
Thanks, I've added a padding function to the library and I've updated the documentation accordingly; it is available via `$.datePicker.defaults.pad(str, width, char = '0')` and has been already applied to the `dateFormat` function.

Regards.
